[book]
authors = ["Alejandro Díaz Pereira"]
language = "es"
multilingual = false
src = "src"
title = "Secretaría de finanzas"
description = "Manual de referencia acerca de las responsabilidades y procesos de las secretarías de finanzas de las asocaciones estudiantiles del TEC"

[output.html.fold]
enable = true
